### PR TITLE
Update ja.po

### PR DESCRIPTION
**Pull request by cat-in-136**
Could you please update the ja.po?

### CODE REVIEW

**Comment by ncelerier** [comment]
Hello cat-in-136. You should probably squash these 2 commits into 1.

**Comment by cat-in-136** [comment]
I see. But why don't you use "[squash and merge](https://help.github.com/articles/about-pull-request-merges/)"?

**Comment by ncelerier** [comment]
Oh, I didn't know about this feature :-)

**Comment by mockturtl** [comment]
ありがとうございます!

Merged.

**Comment by mockturtl** [comment]
> Oh, I didn't know about this feature :-)

Me either!  @cat-in-136 Thanks for the tip.

I found a nifty alias for my [`.gitconfig`](https://github.com/mockturtl/dotfiles/commit/5fbc63f8534c474d646ed08025bcbcebfaec5087), so that `git pr 123` gives me a local branch `pr-123`.  Author information is preserved across edits, so the original submitter still gets credit.

**Pull request closed without merging**
