### PR TITLE
Update fi.po

### PR DESCRIPTION
**Pull request by mockturtl**
Hi @warlon, is it OK if I merge your changes?

### CODE REVIEW

**Comment by warlon** [comment]
You can merge this version if you wish, but I'm planning on improving the
translations further this week.

2015-03-17 1:58 GMT+02:00 mockturtl <notifications@github.com>:

**Comment by mockturtl** [comment]
Great, I'll look for that.

Kiitos!

**Comment by warlon** [comment]
Hi @mockturtl, this translation is now ready to be merged.

**Comment by mockturtl** [comment]
Thanks!

**Pull request closed without merging**
