### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by kghbln**
* Provide missing German translations
* Tweak existing German translations

### CODE REVIEW

**Comment by kghbln** [comment]
@mockturtl FYI and committing. Thanks a lot.

**Comment by mockturtl** [comment]
Danke!

**Comment by mockturtl** [comment]
@kghbln It seems cinnamon-spices is not accepting new releases at this time.  See #180.

I'll publish your changes as soon as the functionality is restored.

**Comment by kghbln** [comment]
> Danke!

Immer wieder gerne!

> I'll publish your changes as soon as the functionality is restored.

Thanks for the note. Keeping fingers crossed.

**Pull request merged**
