### PR TITLE
use correct function for custom css selector

### PR DESCRIPTION
**Pull request by zagortenay333**
This is updated for cinna 3.2. I don't know how you deal with backwards compatibility though.

### CODE REVIEW

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/

**Comment by zagortenay333** [comment]
Not gonna bother tbh. Hope you update this. It's just one function...

**Comment by mockturtl** [comment]
Hi @zagortenay333,

Please understand it's impossible for me to follow changes like this.  I can't conclude from the discussion linked in #175 what the "right" call would be either, and there is no alternative source we can depend on re: breaking changes.

A benefit of having all the Spices "adopted" is that the Cinnamon team can make appropriate changes directly.  Note, I do not myself have commit access.  (Tagging @clefebvre: I would love to be considered, if you think I can help triage, document, etc.)

I do encourage you to submit this change there, and see what they think.

**Comment by zagortenay333** [comment]
Wait, so you've given up the rights on this applet? Are you the person who wrote this applet?

**Comment by mockturtl** [comment]
> Wait, so you've given up the rights on this applet?

Linux Mint [recently decided](http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/) to take over maintenance for all "spices," meaning every entry on [cinnamon-spices.linuxmint.com](https://cinnamon-spices.linuxmint.com/) has source code available at [github.com/linuxmint](https://github.com/linuxmint/).  

Since [cinnamon-spices-applets](https://github.com/linuxmint/cinnamon-spices-applets) is now the official home for all applets, this repo should be considered a "stale fork."

> Are you the person who wrote this applet?

I didn't author most of the code, but it has been "mine" in the sense I made the original port, and [kept it up](https://github.com/mockturtl/cinnamon-weather/tags) over the years.  I would not agree I had or gave up any rights (it's open source!).

Overall, it's positive if the developers best able to make decisions about compatibility can release updates directly.  I'll still be around; the division of labor has just improved.

**Pull request closed without merging**
